### ISSUE TITLE
Position on snd_mix_async

### ISSUE THREAD

**Issue by CristianoLira** [casperstorm/csgo-config#1]
Why aren't you using it in your cfg?

**Comment by casperstorm** [comment]
I **completely** missed this issue. Sorry about that. `snd_mix_async` defaults to 1 however you are right I properly should add it as well just for the sake of completion, since if you disable it you can’t use:

```
snd_mixahead
snd_async_fullyasync
```

Thanks for writing, will close now. Reopen if you have other question - I promise to answer quicker next time :-)
